
##### Customizable variables #####

# Your website URL (e.g. http://jkpark.github.io)
baseURL = "https://jkpark.github.io/"

title = "jkpark's territory"

# Enter your Google Analytics web tracking code (e.g. UA-000000000-1) to activate tracking
googleAnalytics = ""

# Enable Emoji emoticons support for page content; see the Emoji Cheat Sheet(https://www.webfx.com/tools/emoji-cheat-sheet/).
enableEmoji = true

##############################

theme = "jkpark"

languageCode = "ko"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir = false # baseURL/en/, baseURL/kr/ ...

timeout = 10000

# Default number of elements per page in pagination.
paginate = 10

# for extract date in filename
# /content/blog/2006-01-02-post.md will be http://baseURL/blog/post/
[frontmatter]
  date  = [":filename", ":default"]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xHTML = true
      safeHTML = true

  [markup.tableOfContents]
    endLevel = 4
    startLevel = 1

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"