[author]
  name = "JK Park"
  # URL of your avatar or profile pic (you could use your GitHub profile pic)
  avatar = "https://avatars.githubusercontent.com/jkpark?size=36"

[date]
  format = "Jan 2, 2006"

# Enter your Utterance Repo for Comments
[utterance]
  repo = "jkpark/jkpark.github.io-utterances"